language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false
before_install:
  - sudo apt-get install gfortran -y
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("GLMNet"); Pkg.test("GLMNet"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("GLMNet")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
